### PR TITLE
 Updated to build in Windows properly, with binary pipe capability

### LINKED ISSUE #59: ADDR0 .. ADDR3 are undefined
I'm attempting to build the Visual Studio project (considering modernizing / improving it) but I cannot because `ADDR0 .. ADDR3` are undefined.

It looks like the definitions for these were removed some time ago - before I start working on a fix, is there some outside dependency involved now for these, or is this actually a bug?

### PR DESCRIPTION
**Pull request by MartyMacGyver**
These changes should NOT affect other (non-Windows) targets

I used https://github.com/jj1bdx/infnoise-windows as a reference point
for getting this working (and for the idea to not directly include
FTDI source files here but instead direct the user to install them).

Closes #59 as well

### CODE REVIEW

**Comment by MartyMacGyver** [comment]
I see this parent https://github.com/waywardgeek/infnoise and the fork https://github.com/13-37-org/infnoise are out of sync, with 13-37 ahead of this by several commits (which this would also bring in).

Before this gets merged then, what's the plan to resolve that?

**Comment by manuel-domke** [comment]
I'll take care of it! Thanks for your contribution

**Comment by MartyMacGyver** [comment]
Cool! Thank you!

**Comment by MartyMacGyver** [comment]
And FYI, this resolved https://github.com/13-37-org/infnoise/issues/9 as well.

**Pull request merged**
